# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0002_auto_20180104_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaycount',
            name='count',
            field=models.FloatField(default=0),
        ),
    ]
